package PopUp;

import Kelas.Pegawai;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import Kelas.Kategori;
import Kelas.Bagian;
import Kelas.Jabatan;
import View.MainMenu;
import View.MenuKategori;
import View.MenuBagian;
import View.MenuJabatan;
import View.MenuPegawai;
import com.formdev.flatlaf.util.StringUtils;

/**
 *
 * @author Good_Poeple
 */
public class PopUpPegawai extends javax.swing.JFrame {

    public PopUpPegawai() {
        initComponents();
        comboBoxBagian();
        comboBoxJabatan();
        comboBoxKategori();
      //  DateTanggalMasuk.setDate(new Date());
      setTanggalHariIni();
    }
    
    private void setTanggalHariIni() {
        if (DateTanggalMasuk != null) {
            DateTanggalMasuk.setDate(new Date());
        } else {
            System.out.println("JDateChooser belum diinisialisasi!");
        }
    }
    
    void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Kategori");
        model.addColumn("Bagian");
        model.addColumn("Jabatan");
        model.addColumn("NIDN");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Email");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
        model.addColumn("Tanggal_masuk");
        model.addColumn("Status");
        
        

        try {
            Pegawai pg = new Pegawai();
            ResultSet data = pg.tampilPegawai();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("nik "),
                    data.getString("nama"),
                    data.getString("id_kategori"),
                    data.getString("id_bagian"),
                    data.getString("id_jabatan"),
                    data.getString("nidn"),
                    data.getString("jenis_kelamin"),
                    data.getString("email"),
                    data.getString("telepon"),
                    data.getString("alamat"),
                    data.getString("tanggal_masuk"),
                    data.getString("status"),});
            }

        } catch (SQLException sQLException) {

        }

        //tblKepegawaian.setModel(model);
    }
    
    void comboBoxKategori() {

        try {
            Kategori bg = new Kategori();
            ResultSet data = bg.tampilComBoxKategori();

            while (data.next()) {
                String isi = data.getString("nama_kategori");
                cbKategori.addItem(isi);
            }

        } catch (SQLException ex) {

        }

    }
    
    void comboBoxBagian() {

        try {
            Bagian bg = new Bagian();
            ResultSet data = bg.tampilComBoxBagian();

            while (data.next()) {
                String isi = data.getString("nama_bagian");
                cbBagian.addItem(isi);
            }

        } catch (SQLException ex) {

        }

    }
    
    void comboBoxJabatan() {

        try {
            Jabatan jb = new Jabatan();
            ResultSet data = jb.tampilComBoxJabatan();

            while (data.next()) {
                String isi = data.getString("nama_jabatan");
                cbJabatan.addItem(isi);
            }

        } catch (SQLException ex) {

        }

    }
    
    void reset() {
        //autoID();
        txtNIK.setEditable(false);
        txtNama.setText(null);
        cbKategori.setSelectedItem(null);
        cbBagian.setSelectedItem(null);
        cbJabatan.setSelectedItem(null);
        txtNIDN.setText(null);
        cbJK.setSelectedItem(null);
        txtEmail.setText(null);
        txtTelepon.setText(null);
        txtAlamat.setText(null);
        DateTanggalMasuk.setDate(new Date()); // Reset tanggal ke hari ini
        cbStatus.setSelectedItem(null);
    }
    
    public void setData(String nik, String nama, String id_kategori, String id_bagian, String id_jabatan, String nidn,String jenis_kelamin, String email, String telepon, String alamat, String tanggal_masuk, String status) {
        txtNIK.setText(nik);
        txtNama.setText(nama);
        cbKategori.setSelectedItem(id_kategori);
        cbBagian.setSelectedItem(id_bagian);
        cbJabatan.setSelectedItem(id_jabatan);
        txtNIDN.setText(nidn);
        cbJK.setSelectedItem(jenis_kelamin);
        txtEmail.setText(email);
        txtTelepon.setText(telepon);
        txtAlamat.setText(alamat);
        DateTanggalMasuk.setDateFormatString(tanggal_masuk);
        cbStatus.setSelectedItem(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNIDN = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        cbBagian = new javax.swing.JComboBox<>();
        cbJabatan = new javax.swing.JComboBox<>();
        cbJK = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        DateTanggalMasuk = new com.toedter.calendar.JDateChooser();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tambah Data Pegawai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIK");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategori");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bagian");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jabatan");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIDN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Kelamin");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telepon");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Alamat");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tanggal Masuk");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Status");

        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });

        cbBagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBagianActionPerformed(evt);
            }
        });

        cbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNIK)
                            .addComponent(txtNama)
                            .addComponent(txtNIDN)
                            .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbBagian, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbJK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(txtTelepon)
                            .addComponent(txtAlamat)
                            .addComponent(DateTanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambah)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbBagian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DateTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            Pegawai pg = new Pegawai();
            Pegawai.setNik(txtNIK.getText());
            Pegawai.setNama(txtNama.getText());
            Pegawai.setId_kategori(cbKategori.getSelectedItem().toString());
            Pegawai.setId_bagian(cbBagian.getSelectedItem().toString());
            Pegawai.setId_jabatan(cbJabatan.getSelectedItem().toString());
            Pegawai.setNidn(txtNIDN.getText());
            Pegawai.setJenis_kelamin(cbJK.getSelectedItem().toString());
            Pegawai.setEmail(txtEmail.getText());
            Pegawai.setTelepon(txtTelepon.getText());
            Pegawai.setAlamat(txtAlamat.getText());

            java.util.Date utilDate = DateTanggalMasuk.getDate(); // Misalnya ini nama komponen JDateChooser
            if (utilDate != null) {
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                Pegawai.setTanggal_masuk(sqlDate);
            } else {
                Pegawai.setTanggal_masuk(null); // Jika tidak dipilih, set sebagai null
            }
            Pegawai.setStatus(cbStatus.getSelectedItem().toString());
            Kategori kat = new Kategori();
            Bagian bag = new Bagian();
            Jabatan jb = new Jabatan();
            Kategori.setNama_kategori(cbKategori.getSelectedItem().toString());
            kat.Konversi();
            Bagian.setNama_bagian(cbBagian.getSelectedItem().toString());
            bag.Konversi();
            Jabatan.setNama_jabatan(cbJabatan.getSelectedItem().toString());
            jb.Konversi();
            pg.tambahPegawai();
        } catch (Exception e) {
        }

        reset();

        MainMenu.pn_utama.removeAll();
        MainMenu.pn_utama.add(new MenuPegawai());
        MainMenu.pn_utama.repaint();
        MainMenu.pn_utama.revalidate();
        dispose();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try {
            Pegawai pg = new Pegawai();
            Pegawai.setNik(txtNIK.getText());
            Pegawai.setNama(txtNama.getText());
            Pegawai.setId_kategori(cbKategori.getSelectedItem().toString());
            Pegawai.setId_bagian(cbBagian.getSelectedItem().toString());
            Pegawai.setId_jabatan(cbJabatan.getSelectedItem().toString());
            Pegawai.setNidn(txtNIDN.getText());
            Pegawai.setJenis_kelamin(cbJK.getSelectedItem().toString());
            Pegawai.setEmail(txtEmail.getText());
            Pegawai.setTelepon(txtTelepon.getText());
            Pegawai.setAlamat(txtAlamat.getText());
            
            java.util.Date utilDate = DateTanggalMasuk.getDate(); // Misalnya ini nama komponen JDateChooser
            if (utilDate != null) {
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                Pegawai.setTanggal_masuk(sqlDate);
            } else {
                Pegawai.setTanggal_masuk(null); // Jika tidak dipilih, set sebagai null
            }
            Pegawai.setStatus(cbStatus.getSelectedItem().toString());
            Kategori kat = new Kategori();
            Bagian bag = new Bagian();
            Jabatan jb = new Jabatan();
            Kategori.setNama_kategori(cbKategori.getSelectedItem().toString());
            kat.Konversi();
            Bagian.setNama_bagian(cbBagian.getSelectedItem().toString());
            bag.Konversi();
            Jabatan.setNama_jabatan(cbJabatan.getSelectedItem().toString());
            jb.Konversi();
            pg.ubahPegawai();
        } catch (Exception e) {
        }

        reset();
        
        MainMenu.pn_utama.removeAll();
        MainMenu.pn_utama.add(new MenuPegawai());
        MainMenu.pn_utama.repaint();
        MainMenu.pn_utama.revalidate();
        dispose();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            Pegawai pg = new Pegawai();
            Pegawai.setNik(txtNIK.getText());

            pg.hapusPegawai();
        } catch (Exception e) {
        }

        loadTable();
        reset();
        
        MainMenu.pn_utama.removeAll();
        MainMenu.pn_utama.add(new MenuPegawai());
        MainMenu.pn_utama.repaint();
        MainMenu.pn_utama.revalidate();
        dispose();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        // Mendapatkan item yang dipilih dari combo box
//    String selectedCategory = (String) cbKategori.getSelectedItem();
//
//    // Cek apakah kategori yang dipilih adalah "Tenaga Kependidikan"
//    if ("Tenaga Kependidikan".equals(selectedCategory)) {
//        txtNIDN.setVisible(false); // Menyembunyikan txtNIDN
//    } else {
//        txtNIDN.setVisible(true); // Menampilkan txtNIDN
//    }
        String selectedCategory = (String) cbKategori.getSelectedItem();

        // Clear existing items in cbBagian and cbJabatan
        cbBagian.removeAllItems();
        cbJabatan.removeAllItems();

        if ("Tenaga Pendidik".equals(selectedCategory)) {
            // Add items to cbBagian for Tenaga Pendidik
            cbBagian.addItem("Sistem Informasi");
            cbBagian.addItem("Teknik Industri");
            cbBagian.addItem("Pendidikan Teknologi Informasi");
            cbBagian.addItem("Program Studi");

            // Add items to cbJabatan for Tenaga Pendidik
            cbJabatan.addItem("Rektor");
            cbJabatan.addItem("Wakil Rektor 1");
            cbJabatan.addItem("Wakil Rektor 2");
            cbJabatan.addItem("Wakil Rektor 3");
            cbJabatan.addItem("Kaprodi Sistem Informasi");
            cbJabatan.addItem("Kaprodi Pendidikan Teknologi Informasi");
            cbJabatan.addItem("Kaprodi Teknik Industri");
            cbJabatan.addItem("Tidak Ada Jabatan");

            txtNIDN.setVisible(true); // Show txtNIDN
        } else if ("Tenaga Kependidikan".equals(selectedCategory)) {
            // Add items to cbBagian for Tenaga Kependidikan
            cbBagian.addItem("LPPM");
            cbBagian.addItem("BAK");
            cbBagian.addItem("BAU");

            txtNIDN.setVisible(false); // Hide txtNIDN
        }
    }//GEN-LAST:event_cbKategoriActionPerformed

    private void cbBagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBagianActionPerformed
        String selectedBagian = (String) cbBagian.getSelectedItem();

        // Clear existing items in cbJabatan
        cbJabatan.removeAllItems();

        
        if ("Sistem Informasi".equals(selectedBagian)) {
            cbJabatan.addItem("Rektor");
            cbJabatan.addItem("Wakil Rektor 1");
            cbJabatan.addItem("Wakil Rektor 2");
            cbJabatan.addItem("Wakil Rektor 3");
            cbJabatan.addItem("Kaprodi Sistem Informasi");
        
        } else if ("Pendidikan Teknologi Informasi".equals(selectedBagian)) {
            // Add items to cbJabatan for LPPM
            cbJabatan.addItem("Rektor");
            cbJabatan.addItem("Wakil Rektor 1");
            cbJabatan.addItem("Wakil Rektor 2");
            cbJabatan.addItem("Wakil Rektor 3");
            cbJabatan.addItem("Kaprodi Pendidikan Teknologi Informasi");
         
        } else if ("Teknik Industri".equals(selectedBagian)) {
            cbJabatan.addItem("Rektor");
            cbJabatan.addItem("Wakil Rektor 1");
            cbJabatan.addItem("Wakil Rektor 2");
            cbJabatan.addItem("Wakil Rektor 3");
            cbJabatan.addItem("Kaprodi Teknik Industri");
            
        } else if ("Program Studi".equals(selectedBagian)) {
            cbJabatan.addItem("Rektor");
            cbJabatan.addItem("Wakil Rektor 1");
            cbJabatan.addItem("Wakil Rektor 2");
            cbJabatan.addItem("Wakil Rektor 3");
            
        } else if ("LPPM".equals(selectedBagian)) {
            // Add items to cbJabatan for LPPM
            cbJabatan.addItem("Ketua LPPM");
            cbJabatan.addItem("Wakil Ketua LPPM");
            cbJabatan.addItem("Kepala Divisi Penilitian");
            cbJabatan.addItem("Kepala Divisi Pengabdian Masyarakat");
        } else if ("BAK".equals(selectedBagian)) {
            // Add items to cbJabatan for BAK
            cbJabatan.addItem("Kepala BAK");
        } else if ("BAU".equals(selectedBagian)) {
            // Add items to cbJabatan for BAU
            cbJabatan.addItem("Kepala BAU");
        }
    }//GEN-LAST:event_cbBagianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser DateTanggalMasuk;
    public javax.swing.JButton btnHapus;
    public javax.swing.JButton btnTambah;
    public javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbBagian;
    private javax.swing.JComboBox<String> cbJK;
    private javax.swing.JComboBox<String> cbJabatan;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIDN;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables

}
